CREATE TABLE IF NOT EXISTS kbGarrison (
    comic_key SERIAL PRIMARY KEY,
    href TEXT UNIQUE NOT NULL,
    link TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS kbStonewall (
    comic_key SERIAL PRIMARY KEY,
    href TEXT UNIQUE NOT NULL,
    link TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS kbBranco (
    comic_key SERIAL PRIMARY KEY,
    href TEXT UNIQUE NOT NULL,
    link TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS kbBible (
    idx SERIAL PRIMARY KEY,
    book TEXT NOT NULL,
    chapter INT NOT NULL,
    verse INT NOT NULL,
    content TEXT NOT NULL
);