name = "krazy-discord-bot"
main = "dist/index.js"
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-10-30"
node_compat = true

[dev]
local_protocol = "http"

[build]
command = "npm run build"
