name = "khafrabot-api"
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-11-30"
node_compat = true

[dev]
local_protocol = "http"

[build]
command = "npm run build"

