CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS kbIpsum (
    playerId uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    userId VARCHAR(19) NOT NULL UNIQUE,
    firstPlayed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    lastActive TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);