CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS kbCAH;
DROP TABLE IF EXISTS kbBranco;
DROP TABLE IF EXISTS kbGarrison;
DROP TABLE IF EXISTS kbStonewall;

ALTER TABLE kbGuild ADD COLUMN IF NOT EXISTS complete_log_channel TEXT DEFAULT NULL;

ALTER TABLE kbWarns
ALTER COLUMN id TYPE uuid,
ALTER COLUMN id SET DEFAULT uuid_generate_v4(),
DROP COLUMN IF EXISTS k_id;