CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS kbCAH;
DROP TABLE IF EXISTS kbBranco;
DROP TABLE IF EXISTS kbGarrison;
DROP TABLE IF EXISTS kbStonewall;

ALTER TABLE kbGuild ADD COLUMN IF NOT EXISTS complete_log_channel TEXT DEFAULT NULL;